# Generated by Django 3.1.3 on 2021-02-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_photo_legenda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
