# Generated by Django 2.2.8 on 2020-03-15 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adubo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adubo_nome', models.CharField(max_length=30)),
                ('adubo_classificacao', models.CharField(choices=[('Foliar', 'Foliar'), ('Nao Foliar', 'Nao Foliar')], max_length=30)),
                ('adubo_composicao', models.CharField(choices=[('Organico', 'Organico'), ('Sintetico', 'Sintetico')], max_length=20)),
                ('adubo_summary', models.CharField(default='non', max_length=20)),
                ('adubo_slug', models.CharField(default=1, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Adubos',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoAdubo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apontamento_published', models.DateField(default=datetime.datetime.now)),
                ('adubo_nome', models.CharField(max_length=30)),
                ('adubo_dosagem', models.IntegerField()),
                ('adubo_dosagem_he', models.IntegerField(default=1)),
                ('plantio_slug', models.CharField(default=1, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Adubações',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoDefensivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apontamento_published', models.DateField(default=datetime.datetime.now)),
                ('defensivo_nome', models.CharField(max_length=30)),
                ('defensivo_dosagem', models.IntegerField()),
                ('defensivo_volume', models.IntegerField()),
                ('defensivo_volume_he', models.IntegerField(default=1)),
                ('defensivo_praga', models.CharField(max_length=30)),
                ('defensivo_intervalo', models.IntegerField(default=1)),
                ('plantio_slug', models.CharField(default=1, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Pulverizações',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_data_plantiu', models.DateField(default=datetime.datetime.now)),
                ('area_nome', models.CharField(max_length=50)),
                ('area_tamanho', models.IntegerField()),
                ('area_nplantas', models.IntegerField()),
                ('area_cultura', models.CharField(max_length=50)),
                ('area_data_ini_colheita', models.DateField(default=datetime.datetime.now)),
                ('area_summary', models.CharField(default='non', max_length=50)),
                ('area_ativa', models.BooleanField(default=True)),
                ('area_slug', models.CharField(default=1, max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apontamento_published', models.DateField(default=datetime.datetime.now)),
                ('colheita_cultura', models.CharField(default='non', max_length=20)),
                ('colheita_quantia', models.IntegerField()),
                ('colheita_unidade', models.CharField(choices=[('kg', 'kg'), ('Caixas', 'Caixas'), ('Unid', 'Unid')], default='Kg', max_length=20)),
                ('colheita_slug', models.CharField(default=1, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Colheitas',
            },
        ),
        migrations.CreateModel(
            name='Defensivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defensivo_nome', models.CharField(max_length=20)),
                ('defensivo_classificacao', models.CharField(choices=[('Acaricida', 'Acaricida'), ('Bactericida', 'Bactericida'), ('Fungicida', 'Fungicida'), ('Herbicida', 'Herbicida'), ('Inceticida', 'Inceticida'), ('Nematicida', 'Nematicida'), ('Biologico', 'Biologico')], max_length=20)),
                ('defensivo_formulacao', models.CharField(choices=[('Liquido', 'Liquido'), ('Solido', 'Solido')], max_length=20)),
                ('defensivo_reentrada', models.IntegerField(default=1)),
                ('defensivo_dosagem', models.IntegerField(default=30)),
                ('defensivo_principiosativos', models.CharField(max_length=20)),
                ('defensivo_indicacoes', models.CharField(max_length=20)),
                ('defensivo_summary', models.CharField(default='non', max_length=20)),
                ('defensivo_slug', models.CharField(default=1, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Defensivos',
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propriedade_nome', models.CharField(max_length=50)),
                ('propriedade_summary', models.CharField(max_length=50)),
                ('propriedade_ativa', models.BooleanField(default=True)),
                ('proriedade_slug', models.CharField(default=1, max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
            },
        ),
    ]
