# Generated by Django 2.2.8 on 2020-03-15 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caddecampo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defensivo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colheita',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caddecampo.Area', verbose_name='Area colheita'),
        ),
        migrations.AddField(
            model_name='area',
            name='propriedade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caddecampo.Propriedade', verbose_name='Propriedade'),
        ),
        migrations.AddField(
            model_name='aplicacaodefensivo',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caddecampo.Area', verbose_name='Apontamento plantio'),
        ),
        migrations.AddField(
            model_name='aplicacaoadubo',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='caddecampo.Area', verbose_name='Apontamento plantio'),
        ),
        migrations.AddField(
            model_name='adubo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
