# Generated by Django 2.2.8 on 2020-04-14 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddecampo', '0002_auto_20200315_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_data_plantiu_fim',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
