# Generated by Django 3.1.3 on 2021-02-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caddecampo', '0003_area_area_data_plantiu_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adubo',
            name='adubo_classificacao',
            field=models.CharField(choices=[('Foliar', 'Foliar'), ('Nao Foliar', 'Nao Foliar')], max_length=300),
        ),
        migrations.AlterField(
            model_name='adubo',
            name='adubo_composicao',
            field=models.CharField(choices=[('Organico', 'Organico'), ('Sintetico', 'Sintetico')], max_length=200),
        ),
        migrations.AlterField(
            model_name='adubo',
            name='adubo_nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='adubo',
            name='adubo_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='adubo',
            name='adubo_summary',
            field=models.CharField(default='non', max_length=200),
        ),
        migrations.AlterField(
            model_name='aplicacaoadubo',
            name='adubo_nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aplicacaoadubo',
            name='plantio_slug',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='aplicacaodefensivo',
            name='defensivo_nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aplicacaodefensivo',
            name='defensivo_praga',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='aplicacaodefensivo',
            name='plantio_slug',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_cultura',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_slug',
            field=models.CharField(default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_summary',
            field=models.CharField(default='non', max_length=300),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='colheita_cultura',
            field=models.CharField(default='non', max_length=200),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='colheita_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='colheita_unidade',
            field=models.CharField(choices=[('kg', 'kg'), ('Caixas', 'Caixas'), ('Unid', 'Unid')], default='Kg', max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_classificacao',
            field=models.CharField(choices=[('Acaricida', 'Acaricida'), ('Bactericida', 'Bactericida'), ('Fungicida', 'Fungicida'), ('Herbicida', 'Herbicida'), ('Inceticida', 'Inceticida'), ('Nematicida', 'Nematicida'), ('Biologico', 'Biologico')], max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_dosagem',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_formulacao',
            field=models.CharField(choices=[('Liquido', 'Liquido'), ('Solido', 'Solido')], max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_indicacoes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_principiosativos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='defensivo',
            name='defensivo_summary',
            field=models.CharField(default='non', max_length=200),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='propriedade_nome',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='propriedade_summary',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='proriedade_slug',
            field=models.CharField(default=1, max_length=300),
        ),
    ]
